setTimeout(()=>{
    console.log("Anu")
    setTimeout(()=>{
        console.log("Alwin")
        setTimeout(()=>{
            console.log("Athira")
            setTimeout(()=>{
                console.log("Godwin")
                setTimeout(()=>{
                    console.log("Jees")
                },2000)
            },1000)
        },4000)
    },5000)
},7000)